[package]
name = "hp/vise"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Lucide = "virtualbutfake/lucide-roblox@1.1.3"
Future = "egomoose/future@1.0.0"
Parallel = "egomoose/parallel@0.3.0"
